vm1

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -39,6 +39,27 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
 
+    - name: Pull Docker image
+      run: docker pull yeasy/simple-web
+
+    - name: Run Docker unit test
+      run: |
+        docker run -d -p 80:80 --name simple-web yeasy/simple-web
+        docker ps
+        sleep 5 # Wait for the container to start
+
+        response=$(curl -s http://localhost:80)
+        if [[ $response == *"Visit Results"* ]]; then
+          echo "Unit test passed!"
+          exit 0
+        else
+          echo "Unit test failed!"
+          exit 1
+        fi
+     
+    - name: Checkout
+      uses: actions/checkout@v3
+
     # Install the latest version of the Terraform CLI
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2
@@ -190,7 +211,7 @@ jobs:
         key: ${{secrets.SSH_PRIVATE_KEY}}
         # Optional, literal inventory file contents
         inventory: |
-          vm0.deploy-vmsc-ubuntu.westeurope.cloudapp.azure.com ansible_become=yes ansible_ssh_user=adminuser
+          vm1.deploy-vmsc-ubuntu.westeurope.cloudapp.azure.com ansible_become=yes ansible_ssh_user=adminuser
         
 
           
